export const superPaciente = {
  nombre: "q",
  apellidoPat: "q",
  apellidoMat: "q",
  calle: "q",
  colonia: "q",
  cp: 1,
  numeroCasa: 1,
  telefono: 1,
  fechaNacimiento: "2021-05-05",
  religion: "q",
  sexo: "U",
  heredosFamiliares: "q",
  originario: "q",
  residente: "q",
  lenguaIndigena: "q",
  habitaCasa: "q",
  habitantes: 1,
  habitaciones: 1,
  construccionMaterial: "q",
  servicios: [],
  escolaridad: "q",
  ocupacion: "q",
  comidasDiarias: 1,
  ingestaAgua: 1,
  transfusionSangre: "q",
  estadoCivil: "q",
  alergias: [],
  enfermedadesCronicas: "q",
  traumatismo: "q",
  cirujias: 1,
  hospitalizaciones: 1,
  covid19: 1,
  tipoSangre: "q",
  g: 1,
  p: 1,
  a: 1,
  c: 1,
  menarca: 1,
  ciclosMenstruales: 1,
  ivsa: 1,
  mpf: "q",
  deteccionCancer: "q",
  fum: "2021-05-05",
  papanicolau: 1,
  antecedentesPerinatales: "q",
};

export const consultaDatos = {
  idPaciente: "id",
  altura: 1,
  peso: 1,
  pesoPrenatal: 1,
  temperatura: 1,
  freqCardiaca: 1,
  freqRespiratoria: 1,
  presionArterial: "120/80",
  otro: "q",
  motivoConsulta: "q",
  sintomasIniciales: "q",
  laboratorios: "q",
  estudiosPrevios: "q",
  terapeuticaAnterior: "q",
  digestivo: "q",
  respiratorio: "q",
  urinario: "q",
  genitales: "q",
  cardioVasc: "q",
  nervioso: "q",
  endocrino: "q",
  locomotor: "q",
  sintomasGenerales: "q",
  inspeccionGeneral: "q",
  cabeza: "q",
  torax: "q",
  abdomen: "q",
  extPelvicas: "q",
  extToraxicas: "q",
  diagnostico: "q",
  plan: "q",
};

export const data = {
  idPaciente: "id",
};

export function setIdPaciente(id) {
  data.idPaciente = id;
};
